### ISSUE TITLE
Binary compatibility of [de]serialization across releases

### ISSUE THREAD

**Issue by veelo** [deviator/sbin#2]
Hi Oleg,

We are happy users of sbin, it is a very convenient library. Recently we ran into a problem, which is probably due to our use case being different from yours. We use sbin for file i/o, and it is crucial for us that files that have been stored in the past can be opened with any future version of our software. Our first use of sbin was in a small utility that isn't compiled often, and it used release 0.4.0. We then started using it in other programs and sbin made its way into a common library, at release 0.6.0. All was fine until we made some changes to the utility, which was recompiled with 0.6.0: after that it failed to open existing files. It appears that the binary layout of [de]serialization changed between 0.4.0 and 0.5.0. We resolved this issue by upgrading to release 0.8.0 everywhere and manually copying the data over. So we are good for the moment, but it has become clear that we need to guard ourselves against similar problems in the future.

Ideally, we would like to see binary stability in sbin across releases, with an upgrade path whenever the format changes; a proposal follows below. If you have no interest in this then I understand, because it can make future changes to sbin more laborious. In that case we will pin our use of sbin to release 0.8.0 for as long as possible, and if we would need changes in the future, we would probably have to fork sbin and deviate from your development.

The first step in the proposal would be to add or extend existing unit tests with literal byte arrays to prevent unintended format changes.

The second step lays in the future, when/if a format change is deemed necessary. This would entail the implementation of a deserialization function from older formats, for example by means of an extra template parameter like `sbinDeserialize!(Foo, "0.8.0")`. Of course the application must be aware of the sbin release with which the data file was written, but that is something that the application programmer will have to take care of, for example by storing it in the file header. At that point of course also a big fat warning in the release notes would be appreciated.

The downside is that this may complicate sbin's code in the future, but at least it won't show up in user code if the templates are not instantiated with the extra parameter.

What do you think? If you like the idea of providing a binary compatibility guarantee, I'd be happy to start making pull requests for the unit tests (step one).

Best regards,
Bastiaan.

**Comment by deviator** [comment]
Hi Bastiaan!

It's very good idea, because at start of develop this lib I don't used it for storing binary data to files, but now I do this too =)

And I'm sorry what don't I not notice in tag description about breaking changes in binary compatibility.

**Comment by veelo** [comment]
Awesome! Don't worry about the notice, we are glad we learned our lesson at an early stage.

**Comment by veelo** [comment]
I have started on a PR.
